name: pipeline de estudos
on:  workflow_dispatch

jobs:
  job1:
    runs-on: windows-latest

    steps:

      - name: Instalar python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9.9'

      - name: Baixando o repositório
        uses: actions/checkout@v2.4.0
      
      