name: Suite Voo
on:
  workflow_dispatch:
    inputs:
      Suite:
        description: 'Informa qual será a suite executada'
        required: true
        default:  'Voo'

jobs:
  job1:
    runs-on: windows-latest

    steps:

      - name: Instalar python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9.9'

      - name: Instalar Robot Framework e Selenium
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Baixando o repositório
        uses: actions/checkout@v2.4.0

      - name: Executar teste
        run:  robot -d Results Tests/${{ github.event.inputs.Suite }}
      
      - name: Publicar artefatos
        uses: actions/upload-artifact@v2
        if: always()
        with: 
          name: Log suite voo
          path: Results
      