name: pipeline de estudos
on:  workflow_dispatch

jobs:
  job1:
    runs-on: windows-latest

    steps:
      - name: Log baixando repositório
        run: echo ---------- Baixando repositório ---------
      
     - name: Baixando o repositório
       uses: actions/checkout@v2.4.0
       with: actions/checkout
      